### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by hanslelee** [Hi-DN/mosainfo-backend#5]
## 오류 설명
스트리머가 스트리밍을 처음으로 시작하는 경우엔 나타나지 않으나, openCV를 Rerun했을 때 

`[BrokenPipeError: [Errno 32] Broken pipe](https://paka96.tistory.com/31)`

위 에러가 나타나는 것으로 보임.
현재로썬 AWS EC2 인스턴스를 재시작하여 에러를 피하는 중.

**Comment by minji1110** [comment]
@hanslelee 헉 그렇군요.. ㅠㅠ 저희가 ec2 재시작하자마자 작동시켰을때는 모두 잘 되었었던가요..?! 

해결방안에 대해서는 , 저희가 10명 클라이언트 모두가 접속할일은 없겠지만 , 그러면 queue를 하나 두고 관리하는건 어떨까요?
말씀해주신 1. 방식도 좋은 방법같은데 가능한 id를 찾을때까지 계속 ++ 하면서 찾아야하니까, 그냥 queue.pop? 해서 바로 id를 받아오면 어떨까 해서요!
release 되면 다시 push 하구요!

어떤방식이든 일단 적용해보고 Broken Pipe 에러가 해결되는지 보면 좋을 것 같네용!! 수고 많으셨습니다👍👍👍
